# -*- coding: utf-8 -*-
"""Библиотеки Python - 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Uwa372xR7DL7-SDQ9gLPwmiQjArKSjq
"""

import pandas as pd
import numpy as np
from IPython.display import display

df = pd.read_csv('/content/Customers.csv', delimiter=';')
df

"""Найдите людей, у которых возраст больше 30 и доход меньше 30000, найдите людей, которые по профессии юристы и с опытом работы больше 5 лет

"""

display(df[(df['Age'] > 30 ) & (df['Income'] < 30000)])

display(df[(df['Profession'] == 'Lawyer' ) & (df['Work Experience'] < 5)])