# -*- coding: utf-8 -*-
"""Библиотеки Python - 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vCn5gvUStceETW6B7-D8PZTgu1TKAy37
"""

import math as m
import numpy as np

"""Задание 1"""

arr = np.random.randint(1, 10, size=100)
print(arr)
print(f"Процент элементов в векторе > 7 равен " + str((arr > 7).sum()) + "%")

"""Задание 2"""

result = 0
for i in range(0, 1001):
    arr = np.random.randint(1, 10, size=100)
    if (arr > 7).sum() == 20:
       result += 1
print(result)

"""Задание 3"""

a = np.array([np.arange(1, 11)] * 10)
print(a)

"""Задание 4"""

a = np.array([[2, 4], [3, 5], [1, 2]])
print(a.sum(axis=0))