# -*- coding: utf-8 -*-
"""Библиотеки Python - 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I3Mrm4iTiYJEZGG2FpT994-An45lgGI3
"""

import pandas as pd
import numpy as np
from IPython.display import display

data = {'Name':['Alice', 'Ivat', 'Sasha', 'Evgeny', 'Alex'],
        'Age':[20, 25, 30, 40, 50],
        'City':['Vorkuta', 'Moscow', 'Spb', 'Moscow', 'Voronezh'],
        'Sex':['F', 'M', 'F', 'M', 'M'],
        'Salary':[100, 110, 120, 130, 140]}
df = pd.DataFrame(data)

display(df)

df.head(3)

df.tail(3)

df.to_csv('output.csv')
